### ISSUE TITLE
How do I make the Code Samples visible ?

### ISSUE THREAD

**Issue by girishchawla** [Mermade/widdershins#46]
I see [object Object] [ object Object] where I should see the name of a language on the top right. How do I make the language tab show the languages ? I am using petstore.json. I am trying to view the markdown in Whiteboard.

**Comment by MikeRalphson** [comment]
I think whiteboard doesn't (yet) support the feature of having separate display names for the language tabs.

You will probably need to override the `language_tabs` option from something like

```yaml
language_tabs:
  - shell: Shell
  - http: HTTP
  - javascript: JavaScript
  - javascript--nodejs: Node.JS
  - ruby: Ruby
  - python: Python
  - java: Java
```

```yaml
language_tabs:
  - shell
  - html
  - javascript
  - ruby
  - python
  - java
```

Let me know if you need any more information on doing that, or if it doesn't work for you, and I'll install whiteboard and have a look.

**Comment by MikeRalphson** [comment]
I have made a quick fix, and added a file called `whiteboard_env.json` which you can load using the `-e` or `--environment` command-line options, to use simple strings instead of Objects for the language tab names. Let me know if you're using the npm package, and I will cut a new release.

**Comment by girishchawla** [comment]
Yes. I am using npm.  Will I still have to make the changes on the Whiteboard side ?

**Comment by MikeRalphson** [comment]
> Yes. I am using npm. Will I still have to make the changes on the Whiteboard side ?

I've just published v2.2.1 with the fix. If you set the `language_tabs` array to just include strings (either programmatically, or by using an `--environment` file) you won't need to modify whiteboard.

Please let me know how you get on.

**Comment by girishchawla** [comment]
Thanks, Mike. It worked

**Comment by girishchawla** [comment]
BTW node widdershins --version still shows 2.2.0  instead of 2.2.1

**Comment by MikeRalphson** [comment]
> BTW node widdershins --version still shows 2.2.0 instead of 2.2.1

Hmm, I hadn't pushed the last commit from the `npm publish` but that shouldn't have affected it unless you were using a git clone...

**Comment by girishchawla** [comment]
Facing another issue with the code samples. When I click on the method within whiteboard I see the code on the right side, but if I click the parameters I see the documentation in the middle pane and the right pane is empty. The resulting experience is very disjointed.This might have something to do with how whiteboard renders the code content, but I am not sure. Do you have any insight about this ?

**Comment by MikeRalphson** [comment]
I'll spin up whiteboard and have a look!

**Comment by MikeRalphson** [comment]
I think I see what you mean. While whiteboard creates left-menu sub-headings for parameters and responses etc (which is nice), it doesn't seem to compress the middle column white space to align the middle and right-hand columns...

Are there reasons you need to use whiteboard, or can I push you (again -sorry) to take a quick look at shins - [demo here](https://mermade.github.io/shins)?

**Comment by girishchawla** [comment]
OK. Thanks. Will look into shins.

**Comment by MikeRalphson** [comment]
The alternative would be to re-order some of the sections in widdershins to see if that helped, but at the moment that would mean editing the code in `openapi3.js`. In a future re-write I hope it will be just the templates that would need editing.

**Comment by girishchawla** [comment]
Thanks Mike. Will look at Shins. I did not have any specific reason to go to Whiteboard except that it was easier to install and without the ruby stuff. Shins seems to have the same approach.  Wanted to ask an question unrelated to this topic. Maybe I will send you an email directly

**Comment by MikeRalphson** [comment]
No problem, email on profile page. Looking forward to it.

**Comment by MikeRalphson** [comment]
Closing as we seem to have resolved the issue - but please feel free to reopen the issue if necessary.
