### ISSUE TITLE
Security Definition other than api_key is not getting parsed

### ISSUE THREAD

**Issue by arparthasarathi** [Mermade/widdershins#66]
I am using token based authentication for my APIs. So in Swagger definition, I give both basic auth and api_key as security definition. But in Slate markdown only api_key is getting added leaving behind basic method. My swagger JSON includes both the security definition perfectly.

## swagger_doc.json

`....
"securityDefinitions":{
  "basic":
    {
      "type":"basic",
      "description":"Access Token corresponding to the Client needs to be obtained before accessing any authenticated routes",
      "in":"header",
      "name":"basic"
    },
  "api_key":
    {
      "type":"apiKey",
      "in":"header",
      "name":"api_key"
    }
  },
"host":"http://example.com",
...
`

## Slate Markdown Snippet
![screen shot 2017-11-14 at 11 30 49 pm](https://user-images.githubusercontent.com/5359707/32796180-f961cd5e-c993-11e7-9252-8dda283613b7.png)

I could not figure out how to include other ways of authentication defined in OpenAPI Specification.

**Comment by MikeRalphson** [comment]
Is your definition Swagger/OpenAPI 2.0 or OpenAPI 3.0? I'm assuming 2.0.

I've fixed this in the v3.0 branch. Can you test that from github, or shall I release a new beta to npm?

BTW The `in` and `name` properties of the securityDefinition object are only applicable to type `apiKey` not `basic`. https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-15

**Comment by arparthasarathi** [comment]
Hi Mike,

Thanks for your fast reply! 

I tried installing from the branch v3.0, but still the issue persists for me. I cloned the branch v3.0 and installed the package globally to update my widdershins to v3.0.0-beta0.0.

**Comment by MikeRalphson** [comment]
Sorry, I forgot to mention that you need to use the `-x` option (temporarily) with the beta version to enable the latest templates. Please let me know if that works.

**Comment by arparthasarathi** [comment]
Thanks a lot buddy, it worked like a charm ! 

We are looking to use widdershins for our production. It would be great if the stable release is at the earliest. Thanks a ton :)

**Comment by MikeRalphson** [comment]
> We are looking to use widdershins for our production. It would be great if the stable release is at the earliest. Thanks a ton :)

It will be released by the end of the month. Please report any further issues with the beta!

**Comment by arparthasarathi** [comment]
Sure Mike, if I come across any other issues will report ! Thank you

**Comment by arparthasarathi** [comment]
How can I use different Auth Schemes other than **api_key** and **basic** ? 

Swagger supports mentioning various auth schemes like Basic, Bearer, OAuth, Cookie as mentioned in the documentation link below. 

[Swagger - Authentication & Authorization](https://swagger.io/docs/specification/authentication/)

But I could not find any way to mention these various auth schemes.

**Comment by MikeRalphson** [comment]
If your definition is in OpenAPI 2.0 format, you need the following link instead: https://swagger.io/docs/specification/2-0/authentication/

OpenAPI 2.0 only supports basic, apiKey and oAuth2.

If you convert or rewrite your definition to native OpenAPI 3.0 you can use the additional schemes.

**Comment by arparthasarathi** [comment]
Sorry for that Mike, missed it on my part! Thanks for letting me know. You really rock buddy, Cheers 👍

**Comment by MikeRalphson** [comment]
Cool. Thanks for the kind words!
